<Project>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="H.NotifyIcon.WinUI" Version="2.4.1" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.335" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
